### PR TITLE
Cross spawn

### PR DESCRIPTION
**Pull request by ctsstc**
Reverts back to some synchronous calls and implements cross spawn.

### CODE REVIEW

**Comment by ctsstc** [comment]
### Not to self before I run...
`fileNameSanitation` can surely be removed if I change out ember operation run with the cross spawn which will be a nicer, safery method of performing this action.

### Note to others
This was branched off of https://github.com/felixrieseberg/vsc-ember-cli/pull/43 & https://github.com/ctsstc/vsc-ember-cli/tree/fix-ember-not-found-promissy
which reverted some of the work back to the original master @ f92711a8b306cbc36cf2f874dc433735077ac35c

**Comment by t-sauer** [comment]
I wanted to go through your PRs today but now I am a little bit confused. Both this and #46 seem to be changing a lot of the same things. Which one is the one to go forward with?  
If I understand everything correctly this PR is basically to add cross-spawn (which looks great btw) while #46 is also adding cross-spawn + other things?

**Comment by ctsstc** [comment]
@t-sauer This is like part 1, if this is successful then #46 could be part 2, or you can skip part 1 and do part 2 since it includes part 1. 

#46 just uses this as its base to add additional functionality, because I couldn't get much to work on the current master. If you change the base on #46 to this, it will display the changes implemented. 

Honestly I would just probably PR #46

**Comment by locks** [comment]
Closing this for #46 since it's a superset.

**Pull request closed without merging**
