### PR TITLE
ES6 imports and added missing devDependencies

### PR DESCRIPTION
**Pull request by t-sauer**
I changed requires to ES6 imports for more consistency. I also added missing devDependencies.

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Thanks a lot, good stuff!

**Comment by felixrieseberg** [comment]
Checking it closer - don't change `imports`. If it's not a TS module, VS Code won't be able to compile. I'll change it back, so no worries - just for the future.

**Comment by t-sauer** [comment]
This is pretty weird. I am pretty sure it all worked fine on my Mac but I just tried it on my Windows machine and it seems like there are indeed problems.

**Comment by felixrieseberg** [comment]
Mac here, too :smile: No worries, I'm super happy about the contributions. Stuff happens.

**Pull request merged**
